# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_2022"
  # config.vm.boot_timeout = 60
  # config.vm.communicator = "winrm"
  # config.winrm.port = 55985

  config.vm.provider "virtualbox" do |v|
    # v.gui = true
    v.name = "my_vm"
    # v.default_nic_type = "82543GC"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.network :forwarded_port, guest:80, host:8080, id:"http"
  # config.vm.synced_folder "app/wwwroot", "src/"

  config.vm.provision "shell", path: "scripts/install.ps1"
  config.vm.provision "shell", inline: "echo 'legia grac kurwa mac' > test2.txt"
end
